import {
  Organization,
  Batch,
  Student,
  Teacher,
  Note,
  Video,
  Test,
  TestSubmission,
  Attendance,
} from "@/types";

export const mockOrganizations: Organization[] = [
  {
    id: "org-1",
    name: "Allen Career Institute",
    slug: "allen",
    email: "admin@allen.ac.in",
    phone: "9876543210",
    city: "Kota",
    status: "active",
    plan: "enterprise",
    createdAt: "2024-01-15",
    totalStudents: 1240,
    totalBatches: 18,
  },
  {
    id: "org-2",
    name: "Fiitjee Academy",
    slug: "fiitjee",
    email: "admin@fiitjee.com",
    phone: "9876543211",
    city: "Delhi",
    status: "active",
    plan: "pro",
    createdAt: "2024-02-10",
    totalStudents: 842,
    totalBatches: 12,
  },
  {
    id: "org-3",
    name: "Resonance Classes",
    slug: "resonance",
    email: "admin@resonance.ac.in",
    phone: "9876543212",
    city: "Kota",
    status: "pending",
    plan: "free",
    createdAt: "2024-03-05",
    totalStudents: 0,
    totalBatches: 0,
  },
  {
    id: "org-4",
    name: "Motion IIT-JEE",
    slug: "motion",
    email: "admin@motion.ac.in",
    phone: "9876543213",
    city: "Kota",
    status: "pending",
    plan: "free",
    createdAt: "2024-03-08",
    totalStudents: 0,
    totalBatches: 0,
  },
  {
    id: "org-5",
    name: "Narayana Coaching",
    slug: "narayana",
    email: "admin@narayana.ac.in",
    phone: "9876543214",
    city: "Hyderabad",
    status: "suspended",
    plan: "pro",
    createdAt: "2024-01-20",
    totalStudents: 320,
    totalBatches: 6,
  },
];

export const mockBatches: Batch[] = [
  {
    id: "batch-1",
    orgId: "org-1",
    name: "JEE Advanced 2026 - Batch A",
    subject: "Physics",
    description: "Advanced batch for JEE preparation",
    status: "active",
    studentCount: 68,
    createdAt: "2024-06-01",
  },
  {
    id: "batch-2",
    orgId: "org-1",
    name: "JEE Advanced 2026 - Batch B",
    subject: "Chemistry",
    status: "active",
    studentCount: 72,
    createdAt: "2024-06-01",
  },
  {
    id: "batch-3",
    orgId: "org-1",
    name: "NEET 2026 - Morning Batch",
    subject: "Biology",
    status: "active",
    studentCount: 55,
    createdAt: "2024-07-15",
  },
  {
    id: "batch-4",
    orgId: "org-1",
    name: "JEE Mains 2025 - Drop Batch",
    subject: "Mathematics",
    status: "archived",
    studentCount: 40,
    createdAt: "2024-04-01",
  },
];

export const mockStudents: Student[] = [
  {
    id: "stu-1",
    orgId: "org-1",
    name: "Aarav Sharma",
    email: "aarav@example.com",
    phone: "9876501234",
    enrolledBatches: ["batch-1", "batch-3"],
    createdAt: "2024-06-10",
  },
  {
    id: "stu-2",
    orgId: "org-1",
    name: "Priya Patel",
    email: "priya@example.com",
    phone: "9876501235",
    enrolledBatches: ["batch-1"],
    createdAt: "2024-06-11",
  },
  {
    id: "stu-3",
    orgId: "org-1",
    name: "Rohit Kumar",
    email: "rohit@example.com",
    phone: "9876501236",
    enrolledBatches: ["batch-2", "batch-3"],
    createdAt: "2024-06-12",
  },
  {
    id: "stu-4",
    orgId: "org-1",
    name: "Sneha Gupta",
    email: "sneha@example.com",
    phone: "9876501237",
    enrolledBatches: ["batch-2"],
    createdAt: "2024-06-13",
  },
  {
    id: "stu-5",
    orgId: "org-1",
    name: "Vikram Singh",
    email: "vikram@example.com",
    phone: "9876501238",
    enrolledBatches: ["batch-1", "batch-2", "batch-3"],
    createdAt: "2024-06-14",
  },
];

export const mockTeachers: Teacher[] = [
  {
    id: "teacher-1",
    orgId: "org-1",
    name: "Dr. Rajesh Verma",
    email: "rajesh@allen.ac.in",
    phone: "9876500001",
    assignedBatches: ["batch-1"],
    createdAt: "2024-01-20",
  },
  {
    id: "teacher-2",
    orgId: "org-1",
    name: "Prof. Sunita Agarwal",
    email: "sunita@allen.ac.in",
    phone: "9876500002",
    assignedBatches: ["batch-2", "batch-4"],
    createdAt: "2024-01-22",
  },
  {
    id: "teacher-3",
    orgId: "org-1",
    name: "Dr. Amit Joshi",
    email: "amit@allen.ac.in",
    phone: "9876500003",
    assignedBatches: ["batch-3"],
    createdAt: "2024-02-01",
  },
];

export const mockNotes: Note[] = [
  {
    id: "note-1",
    batchId: "batch-1",
    title: "Mechanics - Chapter 1: Laws of Motion",
    description: "Newton's laws, free body diagrams, friction",
    fileUrl: "/files/mechanics-ch1.pdf",
    fileSize: "2.4 MB",
    uploadedBy: "Dr. Rajesh Verma",
    createdAt: "2024-09-01",
  },
  {
    id: "note-2",
    batchId: "batch-1",
    title: "Electrostatics - Full Notes",
    description: "Coulomb's law, electric field, potential",
    fileUrl: "/files/electrostatics.pdf",
    fileSize: "4.1 MB",
    uploadedBy: "Dr. Rajesh Verma",
    createdAt: "2024-09-10",
  },
  {
    id: "note-3",
    batchId: "batch-1",
    title: "Waves & Oscillations",
    fileUrl: "/files/waves.pdf",
    fileSize: "3.2 MB",
    uploadedBy: "Dr. Rajesh Verma",
    createdAt: "2024-09-20",
  },
];

export const mockVideos: Video[] = [
  {
    id: "vid-1",
    batchId: "batch-1",
    title: "Newton's Laws - Lecture 1",
    description: "Introduction to classical mechanics",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    type: "youtube",
    duration: "1:24:30",
    uploadedBy: "Dr. Rajesh Verma",
    createdAt: "2024-09-02",
  },
  {
    id: "vid-2",
    batchId: "batch-1",
    title: "Electrostatics - Problem Solving Session",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    type: "youtube",
    duration: "2:10:00",
    uploadedBy: "Dr. Rajesh Verma",
    createdAt: "2024-09-12",
  },
];

export const mockTests: Test[] = [
  {
    id: "test-1",
    batchId: "batch-1",
    title: "Unit Test 1 - Mechanics",
    instructions: "Read all questions carefully. No negative marking for integer type.",
    status: "available",
    availableFrom: "2024-11-01T09:00:00",
    availableTo: "2024-11-30T23:59:00",
    duration: 180,
    totalMarks: 120,
    shuffleQuestions: true,
    showResultImmediately: true,
    questions: [
      {
        id: "q-1",
        type: "mcq",
        text: "A body of mass 2 kg is acted upon by a force of 10 N. What is the acceleration?",
        options: ["2 m/s²", "5 m/s²", "10 m/s²", "20 m/s²"],
        correctAnswer: "5 m/s²",
        marks: 4,
        negativeMarks: 1,
      },
      {
        id: "q-2",
        type: "mcq",
        text: "Which of the following is Newton's first law?",
        options: [
          "F = ma",
          "An object at rest stays at rest unless acted upon by a net force",
          "For every action there is an equal and opposite reaction",
          "None of the above",
        ],
        correctAnswer: "An object at rest stays at rest unless acted upon by a net force",
        marks: 4,
        negativeMarks: 1,
      },
      {
        id: "q-3",
        type: "integer",
        text: "A car accelerates from 0 to 20 m/s in 4 seconds. Find the acceleration in m/s².",
        correctAnswer: "5",
        marks: 4,
        negativeMarks: 0,
      },
    ],
    createdAt: "2024-10-25",
  },
  {
    id: "test-2",
    batchId: "batch-1",
    title: "Minor Test 2 - Electrostatics",
    status: "scheduled",
    availableFrom: "2024-12-01T09:00:00",
    availableTo: "2024-12-01T12:00:00",
    duration: 120,
    totalMarks: 80,
    shuffleQuestions: false,
    showResultImmediately: false,
    questions: [],
    createdAt: "2024-11-20",
  },
  {
    id: "test-3",
    batchId: "batch-1",
    title: "Full Syllabus Mock Test 1",
    status: "closed",
    availableFrom: "2024-10-01T09:00:00",
    availableTo: "2024-10-01T12:00:00",
    duration: 180,
    totalMarks: 300,
    shuffleQuestions: true,
    showResultImmediately: true,
    questions: [],
    createdAt: "2024-09-25",
  },
];

export const mockTestSubmissions: TestSubmission[] = [
  {
    id: "sub-1",
    testId: "test-1",
    studentId: "stu-1",
    studentName: "Aarav Sharma",
    answers: {
      "q-1": "5 m/s²",
      "q-2": "An object at rest stays at rest unless acted upon by a net force",
      "q-3": "5",
    },
    score: 12,
    totalMarks: 12,
    submittedAt: "2024-11-05T11:30:00",
    timeTaken: 45,
  },
  {
    id: "sub-2",
    testId: "test-1",
    studentId: "stu-2",
    studentName: "Priya Patel",
    answers: { "q-1": "5 m/s²", "q-2": "F = ma", "q-3": "4" },
    score: 7,
    totalMarks: 12,
    submittedAt: "2024-11-05T12:00:00",
    timeTaken: 60,
  },
  {
    id: "sub-3",
    testId: "test-1",
    studentId: "stu-5",
    studentName: "Vikram Singh",
    answers: {
      "q-1": "5 m/s²",
      "q-2": "An object at rest stays at rest unless acted upon by a net force",
      "q-3": "6",
    },
    score: 11,
    totalMarks: 12,
    submittedAt: "2024-11-05T10:50:00",
    timeTaken: 40,
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: "att-1",
    batchId: "batch-1",
    date: "2024-11-10",
    records: [
      { studentId: "stu-1", studentName: "Aarav Sharma", present: true },
      { studentId: "stu-2", studentName: "Priya Patel", present: true },
      { studentId: "stu-5", studentName: "Vikram Singh", present: false },
    ],
  },
  {
    id: "att-2",
    batchId: "batch-1",
    date: "2024-11-11",
    records: [
      { studentId: "stu-1", studentName: "Aarav Sharma", present: true },
      { studentId: "stu-2", studentName: "Priya Patel", present: false },
      { studentId: "stu-5", studentName: "Vikram Singh", present: true },
    ],
  },
];

export const mockPlatformStats = {
  totalOrgs: 42,
  activeOrgs: 38,
  pendingOrgs: 4,
  totalStudents: 12480,
  totalBatches: 186,
  monthlyRevenue: 248000,
};
